apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --volumes hostPath convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch-client
    release-version: "1.0"
  name: elasticsearch-client
spec:
  type: ClusterIP
  ports:
    - port: 1358
      targetPort: 1358
      protocol: TCP
      name: http
  selector:
    io.kompose.service: elasticsearch-client
status:
  loadBalancer: {}
