apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: leenet-gateway-{{ .Values.dnsName }}
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - {{ .Values.dnsName }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: elasticsearch-client.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 1358
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: leenet-gateway-elasticsearch
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - elasticsearch.leenet.link
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: elasticsearch1.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 9200
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: leenet-gateway-fileserver
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gateways:
    - {{ .Values.gateway }}
  hosts:
    - fileserver.leenet.link
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: fileserver.{{ .Values.appNamespace }}.svc.cluster.local
            port:
              number: 3000
