version: '3'
services:
  # Elasticsearch Cluster
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3-amd64
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - fscrawler-net

  # FSCrawler
  fscrawler:
    image: dadoonet/fscrawler:2.7-SNAPSHOT-es6-eng
    container_name: fscrawler
    restart: always
    volumes:
      - ${PWD}/logs:/usr/share/fscrawler/logs
      - /home/alice/ownCloud/:/tmp/es:ro
      - ${PWD}/config/docker-compose:/root/.fscrawler
    depends_on:
      - elasticsearch
    command: fscrawler --rest idx
    networks:
      - fscrawler-net

volumes:
  data:
    driver: local

networks:
  fscrawler-net:
    driver: bridge